### ISSUE TITLE
mopidy.commands Got un-handled exception from RaspberryGPIOFrontend (v1.0.4)

### ISSUE THREAD

**Issue by kokosowy** [pimoroni/mopidy-raspberry-gpio#16]
Hi all!

I get this error, most probably after the update to v1.0.4:

```
gru 16 11:25:46 pirateaudio mopidy[474]: ERROR    [MainThread] mopidy.commands Got un-handled exception from RaspberryGPIOFrontend
gru 16 11:25:46 pirateaudio mopidy[474]: Traceback (most recent call last):
gru 16 11:25:46 pirateaudio mopidy[474]:   File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
gru 16 11:25:46 pirateaudio mopidy[474]:     yield
gru 16 11:25:46 pirateaudio mopidy[474]:   File "/usr/local/lib/python3.7/dist-packages/mopidy/commands.py", line 445, in start_frontends
gru 16 11:25:46 pirateaudio mopidy[474]:     frontend_class.start(config=config, core=core)
gru 16 11:25:46 pirateaudio mopidy[474]:   File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 86, in start
gru 16 11:25:46 pirateaudio mopidy[474]:     obj = cls(*args, **kwargs)
gru 16 11:25:46 pirateaudio mopidy[474]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_raspberry_gpio/frontend.py", line 56, in __init__
```

Can anybody help troubleshooting this, please?

**Comment by beeka** [comment]
From "sudo journalctl -u mopidy" I get:

```
 ERROR    [MainThread] mopidy.commands Got un-handled exception from RaspberryGPIOFrontend
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
      yield
    File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 445, in start_frontends
      frontend_class.start(config=config, core=core)
    File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 91, in start
      obj = cls(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/mopidy_raspberry_gpio/frontend.py", line 56, in __init__
      bouncetime=settings.bouncetime,
  RuntimeError: Failed to add edge detection
```

This was fixed by running `sudo usermod -a -G gpio mopidy`. I'm still not getting the buttons doing anything, but at least the error is gone (broken during an OS update?).
